# Makefile for Beginning Linux Programming 3rd Edition
# Chapter 11

PROGRAM=screen1 moveadd ipmode multiw1 subsc1 keypad color

CFLAGS=-g -lcurses
LDFLAGS=-g

ALL= $(PROGRAM)

all: $(ALL)

clean:
	@rm -f $(ALL) *~ *.o
