# Makefile for Beginning Linux Programming 3rd Edition
# Chapter 11

PROGRAM=hrmglow

CFLAGS=-Wall -lm -g -lcurses -lwiringPi -lwiringPiDev
LDFLAGS=-g

ALL= $(PROGRAM)

all: $(ALL)

clean:
	@rm -f $(ALL) *~ *.o
