# Makefile for Beginning Linux Programming 3rd Edition
# Chapter 11

TIMER=piglow

CFLAGS=-Wall -lm -g -lcurses -lwiringPi -lwiringPiDev
LDFLAGS=-g

ALL= $(TIMER)

all: $(ALL)

clean:
	@rm -f $(ALL) *~ *.o
